#!/usr/bin/env bun
/**
 * Pre-build step: reads all prompt .md files and writes them as string
 * literals into src/agent/prompts/embedded.ts. The compiled Bun binary
 * can't readFileSync from the virtual FS, so this provides a fallback.
 *
 * Usage: bun scripts/embed-prompts.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const PROMPTS_DIR = join(ROOT, "src/agent/prompts");

const PROMPT_FILES = [
  "agents/main.md",
  "agents/planner.md",
  "agents/researcher.md",
  "agents/reviewer.md",
  "agents/generator.md",
  "agents/evaluator.md",
  "agents/builder.md",
  "compaction.md",
  "skill-instructions.md",
];

const entries: string[] = [];
for (const rel of PROMPT_FILES) {
  const content = readFileSync(join(PROMPTS_DIR, rel), "utf-8");
  const escaped = JSON.stringify(content);
  entries.push(`  ${JSON.stringify(rel)}: ${escaped},`);
}

const out = [
  "/** @generated by scripts/embed-prompts.ts — DO NOT EDIT */",
  "export const EMBEDDED: Record<string, string> = {",
  ...entries,
  "};",
  "",
].join("\n");

writeFileSync(join(PROMPTS_DIR, "embedded.ts"), out, "utf-8");
console.log(`[embed-prompts] wrote ${PROMPT_FILES.length} prompts to embedded.ts`);
