/**
 * Bundled prompt files as strings.
 *
 * Primary path: readFileSync from disk (works in dev mode and tsx subprocesses).
 * Fallback: embedded.ts generated by scripts/embed-prompts.ts (required for
 * Bun compiled binaries where the .md files aren't in the virtual FS).
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { EMBEDDED } from "./embedded.ts";

const DIR = dirname(fileURLToPath(import.meta.url));

function read(rel: string): string {
  try {
    return readFileSync(join(DIR, rel), "utf-8");
  } catch {
    const content = EMBEDDED[rel];
    if (content != null) return content;
    throw new Error(`Prompt not found: ${rel} (not on disk and not in embedded.ts — run: bun scripts/embed-prompts.ts)`);
  }
}

export const BUNDLED_PROMPTS: Record<string, string> = {
  "agents/main.md": read("agents/main.md"),
  "agents/planner.md": read("agents/planner.md"),
  "agents/researcher.md": read("agents/researcher.md"),
  "agents/reviewer.md": read("agents/reviewer.md"),
  "agents/generator.md": read("agents/generator.md"),
  "agents/evaluator.md": read("agents/evaluator.md"),
  "agents/builder.md": read("agents/builder.md"),
  "compaction.md": read("compaction.md"),
  "skill-instructions.md": read("skill-instructions.md"),
};
