import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { writeIfChanged } from "./fsutil.ts";
import { EMBEDDED_MCP_CLIENT } from "./emitted-embedded.ts";

const HERE = dirname(fileURLToPath(import.meta.url));

/**
 * Copy the self-authenticating runtime client into the workspace at
 * mcp/_runtime/client.ts. Disk first (dev mode picks up live edits), falling
 * back to the embedded copy generated by scripts/embed-prompts.ts — required
 * in the compiled binary, where HERE is a virtual /$bunfs path readFileSync
 * can't open (same pattern as src/agent/prompts/bundled.ts).
 */
export function writeEmittedClient(workspaceDir: string): void {
  let src: string;
  try {
    src = readFileSync(join(HERE, "emitted", "client.ts"), "utf8");
  } catch {
    src = EMBEDDED_MCP_CLIENT;
  }
  writeIfChanged(join(workspaceDir, "mcp", "_runtime", "client.ts"), src);
}
