#!/usr/bin/env bun
import * as path from "node:path";
import * as os from "node:os";
import * as fs from "node:fs";
import { createCliRenderer } from "@opentui/core";
import { createRoot } from "@opentui/react";
import React from "react";
import { App } from "./ui/app.tsx";
import { Onboarding } from "./ui/onboarding.tsx";
import { SessionPicker } from "./ui/session-picker.tsx";
import { buildGlorp } from "./agent/glorp.ts";
import { CredentialsStore } from "./agent/credentials.ts";
import { listSessions, newSessionId } from "./agent/sessions.ts";
import { getBridge } from "./shared/bridge.ts";
import { GLORP_VERSION } from "./shared/version.ts";
import type { GlorpHandle } from "./agent/glorp.ts";

interface Args {
  workspace: string;
  sessionId: string;
  provider?: string;
  model?: string;
  prompt?: string;
  printOnly: boolean;
  showHelp: boolean;
  showVersion: boolean;
}

function parseArgs(argv: string[]): Args {
  const args: Args = {
    workspace: process.cwd(),
    sessionId: "", // empty = caller will populate (picker or fresh id)
    printOnly: false,
    showHelp: false,
    showVersion: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a === "-h" || a === "--help") args.showHelp = true;
    else if (a === "-v" || a === "--version") args.showVersion = true;
    else if (a === "-C" || a === "--cwd") args.workspace = path.resolve(argv[++i] ?? ".");
    else if (a === "-s" || a === "--session") {
      const next = argv[++i] ?? "";
      // Session IDs become path segments under <dataDir>/sessions/; reject
      // anything that could traverse out of that directory.
      if (next && !/^[A-Za-z0-9._-]+$/.test(next)) {
        process.stderr.write(`error: invalid session id "${next}" (allowed: A-Z a-z 0-9 . _ -)\n`);
        process.exit(2);
      }
      args.sessionId = next || args.sessionId;
    }
    else if (a === "--provider") args.provider = argv[++i];
    else if (a === "-m" || a === "--model") args.model = argv[++i];
    else if (a === "-p" || a === "--print") {
      args.printOnly = true;
      args.prompt = argv[++i];
    } else if (!a.startsWith("-")) {
      // First positional argument is treated as the initial prompt.
      args.prompt = args.prompt ? `${args.prompt} ${a}` : a;
    }
  }
  return args;
}

// session id is generated by `newSessionId()` in src/agent/sessions.ts

const HELP = `glorp — alien coding agent (v${GLORP_VERSION})

USAGE
  glorp [options] [prompt...]
  glorp -p "single one-shot prompt"

OPTIONS
  -C, --cwd <dir>          Workspace root (default: cwd)
  -s, --session <id>       Resume a session by ID (default: timestamp)
      --provider <name>    LLM provider (anthropic|openai|openrouter|gemini|…)
  -m, --model <name>       Model name override
  -p, --print <prompt>     Run one prompt, print result to stdout, exit
  -v, --version            Print version
  -h, --help               This help

ENV
  ANTHROPIC_API_KEY        Used by default if set
  OPENAI_API_KEY           Falls back if no Anthropic key
  OPENROUTER_API_KEY       Falls back if no OpenAI key
  GLORP_DATA_DIR           Override session storage (default ~/.glorp)

SLASH COMMANDS (inside the TUI)
  /plan        Switch to plan-first mode for this turn
  /diff        List files changed since last user message
  /compact     Force a context compaction now
  /clear       Compact and reset the working slate
  /concise     Be terser
  /transmissions  Ask about the homeworld-comms panel
  /quit        Exit glorp

KEY BINDINGS (inside the TUI)
  Ctrl+M       Model switcher (swap profile, tweak reasoning effort)
  Ctrl+S       Session switcher (resume a different conversation)
  Ctrl+T       Transmissions log (full homeworld-comms history)
  Ctrl+P       Permissions list (revoke previously granted/denied tools)
  Esc          Abort the current request

SUBAGENTS
  @planner    Design an approach without writing code
  @researcher Investigate the codebase or fetch docs
  @reviewer   Review a recent change before shipping
`;

async function runHeadless(args: Args): Promise<void> {
  const dataDir = process.env.GLORP_DATA_DIR ?? path.join(os.homedir(), ".glorp");
  ensureApiKey(args);
  const glorp = await buildGlorp({
    workspace: args.workspace,
    sessionId: args.sessionId || newSessionId(),
    dataDir,
    provider: args.provider,
    model: args.model,
  });
  // In print mode, stream text to stdout as it arrives, then print the final.
  process.stdout.write(`glorp> `);
  const { getBridge } = await import("./shared/bridge.ts");
  let final = "";
  getBridge().subscribe((ev) => {
    if (ev.type === "text_delta") process.stdout.write(ev.text);
    if (ev.type === "turn" && ev.turn.kind === "agent") final = ev.turn.text ?? "";
    if (ev.type === "tool_started")
      process.stdout.write(`\n  [${ev.tool.name}] ${describeInput(ev.tool.input)}\n`);
    if (ev.type === "tool_finished") {
      const ok = ev.tool.status === "success";
      process.stdout.write(
        `\n  ${ok ? "✓" : "✗"} ${ev.tool.name} ${ok ? "" : `— ${ev.tool.output?.slice(0, 200) ?? ""}`}\n`,
      );
    }
    if (ev.type === "transmission")
      process.stderr.write(`\n[transmission] ${ev.payload}\n`);
  });
  await glorp.send(args.prompt!);
  process.stdout.write("\n");
  await glorp.shutdown();
  // The streaming subscriber above wrote agent text + tool events to stdout
  // in real time, so there's nothing else to print here. `final` is kept
  // around for the headless contract — if a future caller wants the final
  // text as a single string, expose it; for now stdout is the contract.
  void final;
}

function describeInput(input: unknown): string {
  try {
    const s = JSON.stringify(input);
    return s.length > 120 ? s.slice(0, 117) + "…" : s;
  } catch {
    return String(input);
  }
}

async function runTui(args: Args): Promise<void> {
  const dataDir = process.env.GLORP_DATA_DIR ?? path.join(os.homedir(), ".glorp");
  fs.mkdirSync(dataDir, { recursive: true });
  const credentials = new CredentialsStore(dataDir);

  const needsOnboarding = !args.provider && !credentials.hasAny() && !envHasProvider();

  const renderer = await createCliRenderer({
    targetFps: 60,
    exitOnCtrlC: false,
  });

  // Onboarding first if needed.
  if (needsOnboarding) {
    await runOnboardingFlow(renderer, credentials);
  }

  // Resolve the session id: explicit -s wins; otherwise show the session
  // picker if there are saved sessions; otherwise mint a fresh id silently.
  let sessionId = args.sessionId;
  if (!sessionId) {
    const sessions = await listSessions(dataDir);
    if (sessions.length === 0) {
      sessionId = newSessionId();
    } else {
      sessionId = await runSessionPicker(renderer, dataDir, undefined);
    }
  }

  // Build the first agent.
  let glorp = await buildGlorp({
    workspace: args.workspace,
    sessionId,
    dataDir,
    provider: args.provider,
    model: args.model,
    credentials,
  });

  // Mount the React app. We re-render with the new GlorpHandle when the
  // user switches sessions mid-run.
  const root = createRoot(renderer);
  let stopped = false;

  const onQuit = async () => {
    if (stopped) return;
    stopped = true;
    try {
      await glorp.shutdown();
    } finally {
      renderer.destroy();
      process.exit(0);
    }
  };

  /**
   * Swap to a different session. Tears down the current agent + fleet,
   * builds a new one, and re-renders the App with the fresh handle. The
   * bridge gets a "session_reset" event so the UI store wipes accumulated
   * state (transcript, tasks, inbox) before the new agent starts emitting.
   */
  const swapSession = async (newSessionIdOrNull: string | null) => {
    const nextId = newSessionIdOrNull ?? newSessionId();
    if (nextId === glorp.sessionId) return;
    await glorp.shutdown();
    getBridge().emit({ type: "session_reset" });
    glorp = await buildGlorp({
      workspace: args.workspace,
      sessionId: nextId,
      dataDir,
      provider: args.provider,
      model: args.model,
      credentials,
    });
    render();
  };

  const render = () => {
    root.render(
      React.createElement(App, {
        glorp,
        workspace: args.workspace,
        dataDir,
        onQuit,
        onSwapSession: (s: string | null) => void swapSession(s),
      }),
    );
  };

  if (args.prompt) {
    queueMicrotask(() => void glorp.send(args.prompt!));
  }

  render();

  process.on("SIGINT", () => void onQuit());
  process.on("SIGTERM", () => void onQuit());
}

/**
 * Mounts the session picker at launch (full-screen variant). Resolves
 * with either the user's choice or a fresh session id if they press 'n'.
 */
async function runSessionPicker(
  renderer: any,
  dataDir: string,
  activeSessionId: string | undefined,
): Promise<string> {
  return new Promise<string>((resolve) => {
    const root = createRoot(renderer);
    const finish = (id: string) => {
      root.unmount();
      resolve(id);
    };
    root.render(
      React.createElement(SessionPicker, {
        dataDir,
        variant: "launch",
        activeSessionId,
        onPick: (id: string) => finish(id),
        onNew: () => finish(newSessionId()),
        onClose: () => {
          // Esc at launch quits — no other entry point.
          root.unmount();
          renderer.destroy();
          console.error("\nno session selected.");
          process.exit(0);
        },
      }),
    );
  });
}

function envHasProvider(): boolean {
  return Boolean(
    process.env.ANTHROPIC_API_KEY ||
      process.env.OPENAI_API_KEY ||
      process.env.OPENROUTER_API_KEY ||
      process.env.GEMINI_API_KEY ||
      process.env.GROQ_API_KEY,
  );
}

function ensureApiKey(args: Args): void {
  if (args.provider) return;
  if (envHasProvider()) return;
  // For headless / --print mode we can't pop a TUI, so error out clearly.
  console.error(`
glorp needs a model configured. options:
  • run \`glorp\` interactively to onboard (saves keys to ~/.glorp/credentials.json)
  • set one of: ANTHROPIC_API_KEY · OPENAI_API_KEY · OPENROUTER_API_KEY · GEMINI_API_KEY · GROQ_API_KEY
  • pass --provider <name> --model <id> on the command line
`);
  process.exit(2);
}

/**
 * Mounts the onboarding screen and resolves when the user picks a profile
 * (or rejects when they cancel out). The renderer is reused for the main
 * app afterward — we just unmount the onboarding root.
 */
async function runOnboardingFlow(renderer: any, credentials: CredentialsStore): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const root = createRoot(renderer);
    root.render(
      React.createElement(Onboarding, {
        credentials,
        onComplete: () => {
          root.unmount();
          resolve();
        },
        onCancel: () => {
          root.unmount();
          renderer.destroy();
          console.error("\nonboarding cancelled — no model configured.");
          process.exit(2);
          reject(new Error("cancelled"));
        },
      }),
    );
  });
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  if (args.showHelp) {
    console.log(HELP);
    return;
  }
  if (args.showVersion) {
    console.log(`glorp ${GLORP_VERSION}`);
    return;
  }
  if (args.printOnly) {
    await runHeadless(args);
    return;
  }
  await runTui(args);
}

main().catch((err) => {
  console.error("glorp crashed:", err);
  process.exit(1);
});
